---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keywars-web
  labels:
    app.kubernetes.io/name: keywars
    app.kubernetes.io/component: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keywars
      app.kubernetes.io/component: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keywars-edge
  labels:
    app.kubernetes.io/name: keywars
    app.kubernetes.io/component: edge
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keywars
      app.kubernetes.io/component: edge
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keywars-arena
  labels:
    app.kubernetes.io/name: keywars
    app.kubernetes.io/component: arena
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keywars
      app.kubernetes.io/component: arena
