// <auto-generated />
using System;
using KeyWars.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeyWars.Data.PostgresMigrations
{
    [DbContext(typeof(PostgresKeyWarsDbContext))]
    partial class PostgresKeyWarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeyWars.Domain.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("character varying(360)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Key")
                        .IsUnique();

                    b.HasIndex("UserProfileId", "UnlockedAt");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("KeyWars.Domain.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RatingEligible")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RematchOfChallengeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TrainingTextId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("RematchOfChallengeId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TrainingTextId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("Status", "FinishedAt");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeAttemptBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BindingToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeRoundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<Guid>("TypingAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("TypingAttemptId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.HasIndex("ChallengeRoundId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("ChallengeAttemptBindings");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeParticipant", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Placement")
                        .HasColumnType("integer");

                    b.Property<int>("RatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("RatingBefore")
                        .HasColumnType("integer");

                    b.Property<double>("RatingDelta")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChallengeId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ChallengeParticipants");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("ChallengeRounds");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ChallengeRoundId")
                        .HasColumnType("uuid");

                    b.Property<double>("Consistency")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Placement")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TypingAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("Wpm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TypingAttemptId");

                    b.HasIndex("ChallengeRoundId", "UserProfileId")
                        .IsUnique();

                    b.HasIndex("Status", "FinishedAt", "UserProfileId");

                    b.HasIndex("UserProfileId", "Status", "FinishedAt");

                    b.ToTable("ChallengeRoundResults");
                });

            modelBuilder.Entity("KeyWars.Domain.ContentModerationAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("ActorProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetOwnerProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorProfileId", "CreatedAt");

                    b.HasIndex("TargetOwnerProfileId", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId", "CreatedAt");

                    b.ToTable("ContentModerationAuditEntries");
                });

            modelBuilder.Entity("KeyWars.Domain.GamificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("character varying(360)");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("integer");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpDelta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeenAt", "CreatedAt", "Id");

                    b.HasIndex("UserProfileId", "CreatedAt", "Id");

                    b.HasIndex("UserProfileId", "Source", "SourceId", "EventKey")
                        .IsUnique();

                    b.ToTable("GamificationEvents");
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomParticipantSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("LiveRoomSummaryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Placement")
                        .HasColumnType("integer");

                    b.Property<int>("RatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("RatingBefore")
                        .HasColumnType("integer");

                    b.Property<double>("RatingDelta")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeamNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("Wpm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LiveRoomSummaryId");

                    b.HasIndex("LiveRoomSummaryId", "Status");

                    b.HasIndex("UserProfileId", "Status");

                    b.ToTable("LiveRoomParticipantSummaries");
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AbortedByServer")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("RoundCount")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RoundVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RoomCode");

                    b.HasIndex("FinishedAt", "AbortedByServer");

                    b.ToTable("LiveRoomSummaries");
                });

            modelBuilder.Entity("KeyWars.Domain.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("character varying(360)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("MissionDate")
                        .HasColumnType("date");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "MissionDate");

                    b.HasIndex("UserProfileId", "MissionDate", "Key")
                        .IsUnique();

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("KeyWars.Domain.RewardLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "AwardedAt");

                    b.HasIndex("UserProfileId", "Source", "SourceId")
                        .IsUnique();

                    b.ToTable("RewardLedgerEntries");
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OwnerProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerProfileId");

                    b.ToTable("TextCollections");
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollectionItem", b =>
                {
                    b.Property<Guid>("TextCollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingTextId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("TextCollectionId", "TrainingTextId");

                    b.HasIndex("TrainingTextId");

                    b.HasIndex("TextCollectionId", "SortOrder");

                    b.ToTable("TextCollectionItems");
                });

            modelBuilder.Entity("KeyWars.Domain.TrainingText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CharacterCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RatingEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey");

                    b.HasIndex("OwnerProfileId", "Visibility");

                    b.ToTable("TrainingTexts");
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<int>("Backspaces")
                        .HasColumnType("integer");

                    b.Property<double>("CharactersPerMinute")
                        .HasColumnType("double precision");

                    b.Property<int>("ClientDurationMilliseconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<double>("Consistency")
                        .HasColumnType("double precision");

                    b.Property<int>("ConsistencySampleCount")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCharacters")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer");

                    b.Property<bool>("ExperienceAwarded")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FocusLosses")
                        .HasColumnType("integer");

                    b.Property<int>("IncorrectCharacters")
                        .HasColumnType("integer");

                    b.Property<bool>("LeaderboardEligible")
                        .HasColumnType("boolean");

                    b.Property<double>("MeanWordMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Official")
                        .HasColumnType("boolean");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RawWpm")
                        .HasColumnType("double precision");

                    b.Property<string>("StandardTextKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<int>("TotalCharacters")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TrainingTextId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("WordTimingVariation")
                        .HasColumnType("double precision");

                    b.Property<double>("Wpm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTextId");

                    b.HasIndex("TrainingTextId", "LeaderboardEligible", "Wpm");

                    b.HasIndex("UserProfileId", "Mode", "CreatedAt");

                    b.HasIndex("Completed", "Phase", "PreparedAt", "Id");

                    b.HasIndex("Phase", "FinishedAt", "PreparedAt", "Id");

                    b.HasIndex("Phase", "FinishedAt", "StartedAt", "Id");

                    b.HasIndex("UserProfileId", "Phase", "Completed", "CreatedAt", "Id");

                    b.HasIndex("LeaderboardEligible", "Phase", "Completed", "Official", "Mode", "FinishedAt");

                    b.ToTable("TypingAttempts");
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttemptError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expected")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TypingAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypingAttemptId");

                    b.HasIndex("UserProfileId", "Pattern");

                    b.ToTable("TypingAttemptErrors");
                });

            modelBuilder.Entity("KeyWars.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ArenaRating")
                        .HasColumnType("integer");

                    b.Property<bool>("ChallengesEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultChallengeExpiryDays")
                        .HasColumnType("integer");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Department")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DirectoryObjectGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DirectorySid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<bool>("GhostSharingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GivenName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LeaderboardVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Motto")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreferredSprintSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RatedMatchCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("boolean");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SeasonPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowLiveRankChanges")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLiveWpm")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SoundVolumePercent")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryObjectGuid")
                        .IsUnique();

                    b.HasIndex("DisplayName");

                    b.HasIndex("SamAccountName");

                    b.HasIndex("LeaderboardVisible", "Deleted");

                    b.HasIndex("Department", "LeaderboardVisible", "Deleted");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("KeyWars.Domain.WeaknessObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<double>("AverageMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<int>("Errors")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Pattern")
                        .IsUnique();

                    b.ToTable("WeaknessObservations");
                });

            modelBuilder.Entity("KeyWars.Domain.Achievement", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.Challenge", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("RematchOfChallengeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KeyWars.Domain.TrainingText", null)
                        .WithMany()
                        .HasForeignKey("TrainingTextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeAttemptBinding", b =>
                {
                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.ChallengeRound", null)
                        .WithMany()
                        .HasForeignKey("ChallengeRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TypingAttempt", null)
                        .WithMany()
                        .HasForeignKey("TypingAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeParticipant", b =>
                {
                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRound", b =>
                {
                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRoundResult", b =>
                {
                    b.HasOne("KeyWars.Domain.ChallengeRound", null)
                        .WithMany()
                        .HasForeignKey("ChallengeRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TypingAttempt", null)
                        .WithMany()
                        .HasForeignKey("TypingAttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.GamificationEvent", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomParticipantSummary", b =>
                {
                    b.HasOne("KeyWars.Domain.LiveRoomSummary", null)
                        .WithMany()
                        .HasForeignKey("LiveRoomSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomSummary", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.Mission", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.RewardLedgerEntry", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollection", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollectionItem", b =>
                {
                    b.HasOne("KeyWars.Domain.TextCollection", null)
                        .WithMany()
                        .HasForeignKey("TextCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TrainingText", null)
                        .WithMany()
                        .HasForeignKey("TrainingTextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TrainingText", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttempt", b =>
                {
                    b.HasOne("KeyWars.Domain.TrainingText", null)
                        .WithMany()
                        .HasForeignKey("TrainingTextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttemptError", b =>
                {
                    b.HasOne("KeyWars.Domain.TypingAttempt", null)
                        .WithMany()
                        .HasForeignKey("TypingAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.WeaknessObservation", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
