// <auto-generated />
using System;
using KeyWars.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyWars.Data.Migrations
{
    [DbContext(typeof(KeyWarsDbContext))]
    partial class KeyWarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KeyWars.Domain.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Key")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("KeyWars.Domain.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RatingEligible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrainingTextId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("Status");

                    b.HasIndex("TrainingTextId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeAttemptBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BindingToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChallengeRoundId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Consumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypingAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("TypingAttemptId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.HasIndex("ChallengeRoundId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("ChallengeAttemptBindings");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeParticipant", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Placement")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RatingDelta")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChallengeId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ChallengeParticipants");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("ChallengeRounds");
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ChallengeRoundId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Consistency")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Placement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TypingAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Wpm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TypingAttemptId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("ChallengeRoundId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("ChallengeRoundResults");
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomParticipantSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LiveRoomSummaryId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Placement")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RatingDelta")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Wpm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LiveRoomSummaryId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("LiveRoomParticipantSummaries");
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AbortedByServer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RoomCode");

                    b.ToTable("LiveRoomSummaries");
                });

            modelBuilder.Entity("KeyWars.Domain.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MissionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpReward")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "MissionDate");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerProfileId");

                    b.ToTable("TextCollections");
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollectionItem", b =>
                {
                    b.Property<Guid>("TextCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrainingTextId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("TextCollectionId", "TrainingTextId");

                    b.HasIndex("TrainingTextId");

                    b.HasIndex("TextCollectionId", "SortOrder");

                    b.ToTable("TextCollectionItems");
                });

            modelBuilder.Entity("KeyWars.Domain.TrainingText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OwnerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RatingEligible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey");

                    b.HasIndex("OwnerProfileId", "Visibility");

                    b.ToTable("TrainingTexts");
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<int>("Backspaces")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CharactersPerMinute")
                        .HasColumnType("REAL");

                    b.Property<int>("ClientDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consistency")
                        .HasColumnType("REAL");

                    b.Property<int>("ConsistencySampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExperienceAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FocusLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncorrectCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LeaderboardEligible")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeanWordMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Official")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PreparedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("RawWpm")
                        .HasColumnType("REAL");

                    b.Property<string>("StandardTextKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TrainingTextId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Wpm")
                        .HasColumnType("REAL");

                    b.Property<double>("WordTimingVariation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TrainingTextId");

                    b.HasIndex("UserProfileId", "Mode", "CreatedAt");

                    b.ToTable("TypingAttempts");
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttemptError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actual")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expected")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TypingAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypingAttemptId");

                    b.HasIndex("UserProfileId", "Pattern");

                    b.ToTable("TypingAttemptErrors");
                });

            modelBuilder.Entity("KeyWars.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ArenaRating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChallengesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultChallengeExpiryDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryObjectGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorySid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GhostSharingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LeaderboardVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motto")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredSprintSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatedMatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowLiveRankChanges")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowLiveWpm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryObjectGuid")
                        .IsUnique();

                    b.HasIndex("DisplayName");

                    b.HasIndex("SamAccountName");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("KeyWars.Domain.WeaknessObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<int>("Errors")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Pattern")
                        .IsUnique();

                    b.ToTable("WeaknessObservations");
                });

            modelBuilder.Entity("KeyWars.Domain.Achievement", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.Challenge", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TrainingText", null)
                        .WithMany()
                        .HasForeignKey("TrainingTextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeAttemptBinding", b =>
                {
                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.ChallengeRound", null)
                        .WithMany()
                        .HasForeignKey("ChallengeRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TypingAttempt", null)
                        .WithMany()
                        .HasForeignKey("TypingAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeParticipant", b =>
                {
                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRound", b =>
                {
                    b.HasOne("KeyWars.Domain.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.ChallengeRoundResult", b =>
                {
                    b.HasOne("KeyWars.Domain.ChallengeRound", null)
                        .WithMany()
                        .HasForeignKey("ChallengeRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TypingAttempt", null)
                        .WithMany()
                        .HasForeignKey("TypingAttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomParticipantSummary", b =>
                {
                    b.HasOne("KeyWars.Domain.LiveRoomSummary", null)
                        .WithMany()
                        .HasForeignKey("LiveRoomSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.LiveRoomSummary", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.Mission", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollection", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TextCollectionItem", b =>
                {
                    b.HasOne("KeyWars.Domain.TextCollection", null)
                        .WithMany()
                        .HasForeignKey("TextCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.TrainingText", null)
                        .WithMany()
                        .HasForeignKey("TrainingTextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TrainingText", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttempt", b =>
                {
                    b.HasOne("KeyWars.Domain.TrainingText", null)
                        .WithMany()
                        .HasForeignKey("TrainingTextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.TypingAttemptError", b =>
                {
                    b.HasOne("KeyWars.Domain.TypingAttempt", null)
                        .WithMany()
                        .HasForeignKey("TypingAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyWars.Domain.WeaknessObservation", b =>
                {
                    b.HasOne("KeyWars.Domain.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
