using KeyWars.Domain;

namespace KeyWars.Services;

public sealed record LiveRoomMemento(
    Guid Id,
    Guid CreatorProfileId,
    string Code,
    string Title,
    string Text,
    LiveRoomMode Mode,
    LiveRoomVisibility Visibility,
    int RoundCount,
    int MaxParticipants,
    DateTimeOffset CreatedAt,
    LiveRoomPhase Phase,
    int CurrentRound,
    int RoundVersion,
    long StateVersion,
    bool LobbyLocked,
    DateTimeOffset PhaseChangedAt,
    DateTimeOffset? CountdownStartsAt,
    DateTimeOffset? RaceStartsAt,
    DateTimeOffset? RoundEndsAt,
    string? CloseReason,
    bool Started,
    bool Finished,
    CompletionReceipt? CompletionReceipt,
    CompletionState? PersistenceState,
    DateTimeOffset? StartedAt,
    DateTimeOffset? FinishedAt,
    IReadOnlyList<Guid> ExcludedProfileIds,
    IReadOnlyList<Guid> InvitedProfileIds,
    IReadOnlyDictionary<int, int> TeamRoundWins,
    IReadOnlyList<LiveParticipantMemento> Participants);

public sealed record LiveParticipantMemento(
    Guid ProfileId,
    string DisplayName,
    ParticipantStatus Status,
    DateTimeOffset JoinedAt,
    int? TeamNumber,
    bool Ready,
    int Sequence,
    int CorrectCharacters,
    string TypedTextPreview,
    double Wpm,
    int? Placement,
    DateTimeOffset? FinishedAt,
    DateTimeOffset? DisconnectedAt,
    int DurationMilliseconds,
    double Accuracy,
    int SeriesPoints,
    int RoundWins,
    int FinishedRounds,
    int CompletedRounds,
    int TotalDurationMilliseconds,
    double TotalWpm,
    double TotalAccuracy);
